### ISSUE TITLE
Eigenvalues beyond range [-2/3,2/3] detected! 

### ISSUE THREAD

**Issue by lkampoli** [HexFluid/TurbAna#1]
Hello, 

thank you for this project, it is very useful. 
I am trying to use it my my own data (attached), the Reynolds stress tensor extracted along a vertical line at a fixed x with openfoam sampling post-processing utility. When I run, for example:

`
import h5py
import os
import numpy as np
import TurbAna
import matplotlib.pyplot as plt

#current_path = os.getcwd() # assuming Python launched in the 'TurbAna' dir
#data_path    = os.path.join(current_path,'tutorials','bstep_data','bstep_DNS.h5')

data = np.genfromtxt('XoRm0.1_R.txt', delimiter=' ')

TurbStat = data[:,1:]
print(TurbStat.shape)
print(TurbStat)

Grid = np.ones((TurbStat.shape[0],2), dtype=np.float64)
Grid[:,0] = np.ones(TurbStat.shape[0]) * -0.1
Grid[:,1] = data[:,0]
print(Grid.shape)
print(Grid) 

sel_idx = (Grid[:,0]==-0.1) # selected profile at x/R = -0.1
print(sel_idx.shape)
print(sel_idx)

RST = TurbAna.ReynoldsStressTensor(TurbStat[sel_idx,:]) # Reynolds stress tensor
coors = RST.BaryTriCoor()                               # Barycentric map coordinates: xB and yB
RGB = RST.AniRGB()                                      # RGB color values from turbulence anisotropy eigenvalues

fig = TurbAna.plot_bary_tri()
plt.scatter(coors[:,0], coors[:,1], facecolors=RGB, zorder=0)
plt.show()

fig = TurbAna.plot_bary_tri_colormap()
plt.scatter(coors[:,0], coors[:,1], facecolors=RGB, zorder=0)
plt.show()

fig = TurbAna.plot_turb_tri()
plt.scatter(coors[:,0], coors[:,1], facecolors=RGB, zorder=0)
plt.show()

fig = TurbAna.plot_Lumley_tri()
plt.scatter(coors[:,0], coors[:,1], facecolors=RGB, zorder=0)
plt.show()

`

I get the error:
Eigenvalues beyond range [-2/3,2/3] detected! Please check data.

Is there any constraints on the input data format? Or what am I doing wrong?

Thank you for your help!
Lorenzo

[XoRm0.1_R.txt](https://github.com/HexFluid/TurbAna/files/9206551/XoRm0.1_R.txt)

**Comment by HexFluid** [comment]
Hi Lorenzo,

Could you check the following:
(1) Do all the grid points complain about "beyond range" or just a few grid points? For the latter, it can happen and can be ignored.
(2) Are all the data in SI units?
(3) Is your turbulence statistics data obtained from pure RANS or pure LES/DNS? When using hybrid RANS/LES (e.g., DES) and summing up both the modeled and resolved stresses, it can return the "beyond range" error. In that case, I recommend using the resolved stresses only.
(4) Did you prepare the "TurbStat" array in the correct order? (e.g., uu,vv,ww,uv for 2D cases; uu,vv,ww,uv,uw,vw for 3D cases) 

Please let me know if this helps.

Best,
Xiao

**Comment by lkampoli** [comment]
Hello Xiao,

thank for your hints. Actually, respect to point 1-4 you mentioned, my dataset seems ok. So, I am still investigating. I tried another dataset taken from https://www.kaggle.com/datasets/ryleymcconkey/ml-turbulence-dataset and it produces the plotted. Nevertheless, sometimes the points fall out of the boundary of the plot. Is that expected?

Thank you.

**Comment by HexFluid** [comment]
Hi Lorenzo,

I do observe in previous publications the anisotropy states of some grid points exceed the triangle range, e.g., Fig. 14 and 15 of https://doi.org/10.1063/5.0048909. However, I am not sure if this is physically and numerically correct. 

I am currently in the final write-up stage of my PhD and have limited time on Github. After this stage I will investigate this issue.   

Best,
Xiao

**Comment by HexFluid** [comment]
> Hello Xiao,
> 
> thank for your hints. Actually, respect to point 1-4 you mentioned, my dataset seems ok. So, I am still investigating. I tried another dataset taken from https://www.kaggle.com/datasets/ryleymcconkey/ml-turbulence-dataset and it produces the plotted. Nevertheless, sometimes the points fall out of the boundary of the plot. Is that expected?
> 
> Thank you.

Hi Lorenzo,

I took a quick check of your dataset - it seems that some items in the columns corresponding to uu, vv and ww have negative signs, which is incorrect. I am not sure if this is the main reason for the complain, but it will be good to fix this first.

Also please let me know if you have fixed this issue by yourself already.

Cheers,
Xiao
